/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Slot } from './Slot';
import {
    SlotFromJSON,
    SlotFromJSONTyped,
    SlotToJSON,
} from './Slot';

/**
 * 
 * @export
 * @interface CreateChangeset
 */
export interface CreateChangeset {
    /**
     * 
     * @type {string}
     * @memberof CreateChangeset
     */
    offerId: string;
    /**
     * 
     * @type {Slot}
     * @memberof CreateChangeset
     */
    slot: Slot;
}

/**
 * Check if a given object implements the CreateChangeset interface.
 */
export function instanceOfCreateChangeset(value: object): value is CreateChangeset {
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    if (!('slot' in value) || value['slot'] === undefined) return false;
    return true;
}

export function CreateChangesetFromJSON(json: any): CreateChangeset {
    return CreateChangesetFromJSONTyped(json, false);
}

export function CreateChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'offerId': json['offer_id'],
        'slot': SlotFromJSON(json['slot']),
    };
}

export function CreateChangesetToJSON(value?: CreateChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'offer_id': value['offerId'],
        'slot': SlotToJSON(value['slot']),
    };
}

