/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerChangeset
 */
export interface CustomerChangeset {
    /**
     * 
     * @type {string}
     * @memberof CustomerChangeset
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerChangeset
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerChangeset
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerChangeset
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the CustomerChangeset interface.
 */
export function instanceOfCustomerChangeset(value: object): value is CustomerChangeset {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    return true;
}

export function CustomerChangesetFromJSON(json: any): CustomerChangeset {
    return CustomerChangesetFromJSONTyped(json, false);
}

export function CustomerChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function CustomerChangesetToJSON(value?: CustomerChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone': value['phone'],
    };
}

