/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
} from './Price';

/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {Date}
     * @memberof Offer
     */
    createdAt: Date;
    /**
     * The duration of the offer in minutes
     * @type {number}
     * @memberof Offer
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    id: string;
    /**
     * 
     * @type {Price}
     * @memberof Offer
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    serviceId: string;
}

/**
 * Check if a given object implements the Offer interface.
 */
export function instanceOfOffer(value: object): value is Offer {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function OfferFromJSON(json: any): Offer {
    return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Offer {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'duration': json['duration'],
        'id': json['id'],
        'price': PriceFromJSON(json['price']),
        'providerId': json['provider_id'],
        'serviceId': json['service_id'],
    };
}

export function OfferToJSON(value?: Offer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'duration': value['duration'],
        'id': value['id'],
        'price': PriceToJSON(value['price']),
        'provider_id': value['providerId'],
        'service_id': value['serviceId'],
    };
}

