/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
} from './Price';

/**
 * 
 * @export
 * @interface ProviderOfferCreateChangeset
 */
export interface ProviderOfferCreateChangeset {
    /**
     * The duration of the offer in minutes
     * @type {number}
     * @memberof ProviderOfferCreateChangeset
     */
    duration: number;
    /**
     * 
     * @type {Price}
     * @memberof ProviderOfferCreateChangeset
     */
    price: Price;
    /**
     * 
     * @type {string}
     * @memberof ProviderOfferCreateChangeset
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderOfferCreateChangeset
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ProviderOfferCreateChangeset interface.
 */
export function instanceOfProviderOfferCreateChangeset(value: object): value is ProviderOfferCreateChangeset {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ProviderOfferCreateChangesetFromJSON(json: any): ProviderOfferCreateChangeset {
    return ProviderOfferCreateChangesetFromJSONTyped(json, false);
}

export function ProviderOfferCreateChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderOfferCreateChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'price': PriceFromJSON(json['price']),
        'providerId': json['provider_id'],
        'serviceId': json['service_id'],
    };
}

export function ProviderOfferCreateChangesetToJSON(value?: ProviderOfferCreateChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'duration': value['duration'],
        'price': PriceToJSON(value['price']),
        'provider_id': value['providerId'],
        'service_id': value['serviceId'],
    };
}

