/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReservationStatus = {
    Confirmed: 'confirmed',
    Cancelled: 'cancelled',
    Hold: 'hold',
    Pending: 'pending'
} as const;
export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];


export function instanceOfReservationStatus(value: any): boolean {
    for (const key in ReservationStatus) {
        if (Object.prototype.hasOwnProperty.call(ReservationStatus, key)) {
            if (ReservationStatus[key as keyof typeof ReservationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReservationStatusFromJSON(json: any): ReservationStatus {
    return ReservationStatusFromJSONTyped(json, false);
}

export function ReservationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationStatus {
    return json as ReservationStatus;
}

export function ReservationStatusToJSON(value?: ReservationStatus | null): any {
    return value as any;
}

