/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationStatus } from './ReservationStatus';
import {
    ReservationStatusFromJSON,
    ReservationStatusFromJSONTyped,
    ReservationStatusToJSON,
} from './ReservationStatus';

/**
 * 
 * @export
 * @interface ReservationUpdateChangeset
 */
export interface ReservationUpdateChangeset {
    /**
     * 
     * @type {string}
     * @memberof ReservationUpdateChangeset
     */
    customerId?: string | null;
    /**
     * 
     * @type {ReservationStatus}
     * @memberof ReservationUpdateChangeset
     */
    status?: ReservationStatus;
}



/**
 * Check if a given object implements the ReservationUpdateChangeset interface.
 */
export function instanceOfReservationUpdateChangeset(value: object): value is ReservationUpdateChangeset {
    return true;
}

export function ReservationUpdateChangesetFromJSON(json: any): ReservationUpdateChangeset {
    return ReservationUpdateChangesetFromJSONTyped(json, false);
}

export function ReservationUpdateChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationUpdateChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'status': json['status'] == null ? undefined : ReservationStatusFromJSON(json['status']),
    };
}

export function ReservationUpdateChangesetToJSON(value?: ReservationUpdateChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customer_id': value['customerId'],
        'status': ReservationStatusToJSON(value['status']),
    };
}

