/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RRuleSet
 */
export interface RRuleSet {
    /**
     * 
     * @type {Array<Date>}
     * @memberof RRuleSet
     */
    exdates: Array<Date>;
    /**
     * A list of RRULE to **exclude** from the set
     * @type {Array<string>}
     * @memberof RRuleSet
     */
    exrules: Array<string>;
    /**
     * 
     * @type {Array<Date>}
     * @memberof RRuleSet
     */
    rdates: Array<Date>;
    /**
     * A list of RRULE to **include** in the set
     * @type {Array<string>}
     * @memberof RRuleSet
     */
    rrules: Array<string>;
}

/**
 * Check if a given object implements the RRuleSet interface.
 */
export function instanceOfRRuleSet(value: object): value is RRuleSet {
    if (!('exdates' in value) || value['exdates'] === undefined) return false;
    if (!('exrules' in value) || value['exrules'] === undefined) return false;
    if (!('rdates' in value) || value['rdates'] === undefined) return false;
    if (!('rrules' in value) || value['rrules'] === undefined) return false;
    return true;
}

export function RRuleSetFromJSON(json: any): RRuleSet {
    return RRuleSetFromJSONTyped(json, false);
}

export function RRuleSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RRuleSet {
    if (json == null) {
        return json;
    }
    return {
        
        'exdates': json['exdates'],
        'exrules': json['exrules'],
        'rdates': json['rdates'],
        'rrules': json['rrules'],
    };
}

export function RRuleSetToJSON(value?: RRuleSet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exdates': value['exdates'],
        'exrules': value['exrules'],
        'rdates': value['rdates'],
        'rrules': value['rrules'],
    };
}

