/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceCreateChangeset
 */
export interface ServiceCreateChangeset {
    /**
     * 
     * @type {string}
     * @memberof ServiceCreateChangeset
     */
    name: string;
}

/**
 * Check if a given object implements the ServiceCreateChangeset interface.
 */
export function instanceOfServiceCreateChangeset(value: object): value is ServiceCreateChangeset {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ServiceCreateChangesetFromJSON(json: any): ServiceCreateChangeset {
    return ServiceCreateChangesetFromJSONTyped(json, false);
}

export function ServiceCreateChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCreateChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ServiceCreateChangesetToJSON(value?: ServiceCreateChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

