/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
} from './Status';

/**
 * 
 * @export
 * @interface ServiceUpdateChangeset
 */
export interface ServiceUpdateChangeset {
    /**
     * 
     * @type {string}
     * @memberof ServiceUpdateChangeset
     */
    name?: string | null;
    /**
     * 
     * @type {Status}
     * @memberof ServiceUpdateChangeset
     */
    status?: Status | null;
}



/**
 * Check if a given object implements the ServiceUpdateChangeset interface.
 */
export function instanceOfServiceUpdateChangeset(value: object): value is ServiceUpdateChangeset {
    return true;
}

export function ServiceUpdateChangesetFromJSON(json: any): ServiceUpdateChangeset {
    return ServiceUpdateChangesetFromJSONTyped(json, false);
}

export function ServiceUpdateChangesetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceUpdateChangeset {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
    };
}

export function ServiceUpdateChangesetToJSON(value?: ServiceUpdateChangeset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'status': StatusToJSON(value['status']),
    };
}

