/* tslint:disable */
/* eslint-disable */
/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Slot
 */
export interface Slot {
    /**
     * 
     * @type {Date}
     * @memberof Slot
     */
    end: Date;
    /**
     * 
     * @type {Date}
     * @memberof Slot
     */
    start: Date;
}

/**
 * Check if a given object implements the Slot interface.
 */
export function instanceOfSlot(value: object): value is Slot {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    return true;
}

export function SlotFromJSON(json: any): Slot {
    return SlotFromJSONTyped(json, false);
}

export function SlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Slot {
    if (json == null) {
        return json;
    }
    return {
        
        'end': (new Date(json['end'])),
        'start': (new Date(json['start'])),
    };
}

export function SlotToJSON(value?: Slot | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'end': ((value['end']).toISOString()),
        'start': ((value['start']).toISOString()),
    };
}

