/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Slot } from '../models/Slot';
import { HttpFile } from '../http/http';

export class CreateChangeset {
    'offerId': string;
    'slot': Slot;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offerId",
            "baseName": "offer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "Slot",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateChangeset.attributeTypeMap;
    }

    public constructor() {
    }
}

