/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Price } from '../models/Price';
import { HttpFile } from '../http/http';

export class Offer {
    'createdAt': Date;
    /**
    * The duration of the offer in minutes
    */
    'duration': number;
    'id': string;
    'price': Price;
    'providerId': string;
    'serviceId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Price",
            "format": ""
        },
        {
            "name": "providerId",
            "baseName": "provider_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Offer.attributeTypeMap;
    }

    public constructor() {
    }
}

