/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReservationStatus } from '../models/ReservationStatus';
import { HttpFile } from '../http/http';

export class ReservationUpdateChangeset {
    'customerId'?: string | null;
    'status'?: ReservationStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ReservationStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReservationUpdateChangeset.attributeTypeMap;
    }

    public constructor() {
    }
}



