/**
 * Cale API
 *  # About cale.app provides a scheduling API that helps developers to integrate scheduling features into their applications. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Slot } from '../models/Slot';
import { HttpFile } from '../http/http';

export class SlotsPayload {
    'duration': number;
    'offer': string;
    'slots': Array<Slot>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "offer",
            "baseName": "offer",
            "type": "string",
            "format": ""
        },
        {
            "name": "slots",
            "baseName": "slots",
            "type": "Array<Slot>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SlotsPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

